permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: MusicPoint
  description: |
    A website with everything ranging from CDs, Vinyl, and Digital downloads for a wide range of music artists.
  font_url: "https://fonts.googleapis.com/css?family=Roboto+Slab:300,400,700|Sarabun:300,400,600,700"
  colors:
    background: "--color-primary-light"
    accent: "--color-neutral-light-grey"
    patterns:
      brand.logos: "--color-primary"
  layouts:
    defaults: |
      The default layout should be used for almost every site page, it contains the header and footer.
  rationales:
    typefaces.primary: |
      Sarabun was selected because it is appealing as a sans-serif font while also being unique giving MusicPoint it's on identity.
    typefaces.secondary: |
      Roboto Slab was used for the logo type as well as certain headers to help contrast with Sarabun, based on what MusicPoint sells it makes more sense to contrast with a slab rather than a serif.
    colors.primary: |
      The dark blue is used for header, footer, marked text, and the logo, the lighter verison is used as the backgroun for the bulk of the website.
    colors.secondary: |
      The lighter blue is used for accenting, buttons, and borders.
    colors.accent: |
      The accent blue is used for certain hover states, and footer text.
collections:
  products:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
