title: "Forms"
description: |
  Forms are used for inputing information when purchasing an item.

patterns:
  text-input:
    title: "Text Input"
    description: |
      The text input is used for a majority of information on the checkout page.
    fields:
    - name: text-label
      type: string
      example: "Input text"
  email-input:
    title: "Email Input"
    description: |
      The email input is used for a inputting a valid email address on the checkout page.
    fields:
    - name: email-label
      type: string
      example: "Email"
  dropdown-input:
    title: "Dropdown Input"
    description: |
      The dropdown input is used for selecting a province and country on the checkout page.
    fields:
    - name: drop-label
      type: string
      example: "Province"
    - name: drop-option
      type: string
      example: "Ontario"
  checkbox-input:
    title: "Checkbox Input"
    description: |
      The checkbox input is used for selecting a confirmation on the checkout page.
    fields:
    - name: checkbox-label
      type: string
      example: "Accept"
